---
name: RaisingEgg
author: NoobMCBG
main: NoobMCBG\RaisingEgg\Main
api: 3.0.0
version: 1.0.0
commands:
 egg:
  description: "Egg"
  aliases: [raisingegg]
permission:
  egg.command: 
    description: Upgrade Egg
    default: op
...
